{{- if .Values.environment.configmap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $key, $val := .Values.environment.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}