apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{- include "your-chart-name.serviceNameCustom" . | nindent 4 }}-service
  {{- end }}
  labels:
    {{- include "your-chart-name.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $val := .Values.service.ports }}
  - name: {{ $val.name }}
    targetPort: {{ $val.containerPort }}
    port: {{ $val.port }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "your-chart-name.selectorLabels" . | nindent 4 }}
